---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodeBuild Projects for EKS'

Parameters:

  CodeBuildArtifactsBucketName:
    Type: String
    Default: codebuild-artifacts
    Description: Name for the bucket where CodeBuild will save output artifacts

  SourceLocation:
    Type: String
    Default: https://github.com/user/repo
    Description: Location of source code for the create-eks codebuild projects

  SourceType:
    Type: String
    Default: GITHUB
    AllowedValues:
      - GITHUB
      - CODECOMMIT

  EKSAdminCLI:
    Type: String
    Default: ""
    Description: Default CLI account arn to have admin access to EKS from command line

# TODO: Add codecommit permissions
Resources:

  CreateEKSRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: create-eks-crossplane
        AssumeRolePolicyDocument:
          Statement:
            - Action:
                - sts:AssumeRole
              Effect: Allow
              Principal:
                Service: codebuild.amazonaws.com
          Version: '2012-10-17'
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/PowerUserAccess
          - arn:aws:iam::aws:policy/IAMFullAccess

  CodeBuildArtifactsBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref CodeBuildArtifactsBucketName
      Tags:
        -
          Key: cloudformation-stack
          Value: !Ref AWS::StackId

  CreateEKSProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Name: files
        Location: !Ref CodeBuildArtifactsBucket
        OverrideArtifactName: true
        NamespaceType: NONE
        Packaging: NONE
        Path: create-eks
        Type: S3
      BadgeEnabled: true
      Cache:
        Type: NO_CACHE
      Description: Creates and EKS cluster and supporting infrastructure/roles/policies
      EncryptionKey:
        Fn::Join: [ "", [ "arn:aws:kms:", { Ref: "AWS::Region" }, ":", { Ref: "AWS::AccountId" }, ":alias/aws/s3"]]
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: infrastructureascode/aws-cli
        PrivilegedMode: false
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          -
            Name: K8S_NAME
            Type: PLAINTEXT
            Value: "crossplane-infra"
          -
            Name: BUCKET_NAME
            Type: PLAINTEXT
            Value: "crossplane-infra"
          -
            Name: MANAGING_PROFILE
            Type: PLAINTEXT
            Value: !Ref EKSAdminCLI

      Name: create-eks
      ServiceRole: !Ref CreateEKSRole
      Source:
        BuildSpec: buildspec-infra.yaml
        GitCloneDepth: 1
        InsecureSsl: false
        Location: !Ref SourceLocation
        Type: !Ref SourceType
      Tags:
        -
          Key: cloudformation-stack
          Value: !Ref AWS::StackId
      TimeoutInMinutes: 45

Outputs:

  CodeBuildArtifactsBucket:
    Description: Bucket where codebuild artifacts are placed
    Value: !Ref CodeBuildArtifactsBucket

  CreateEKSRole:
    Description: Role that the codebuild projects use for EKS deployments.
    Value: !Ref CreateEKSRole
